config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'home#index'

  get 'uk-treaties/' => 'home#index', :as => 'home'
  
  get 'uk-treaties/treaties' => 'treaty#index', :as => 'treaty_list'
  get 'uk-treaties/treaties/:treaty' => 'treaty#show', :as => 'treaty_show'
  
  get 'uk-treaties/treaty-types' => 'treaty_type#index', :as => 'treaty_type_list'
  get 'uk-treaties/treaty-types/:treaty_type' => 'treaty_type#show', :as => 'treaty_type_show'
  
  get 'uk-treaties/subjects' => 'subject#index', :as => 'subject_list'
  get 'uk-treaties/subjects/:subject' => 'subject#show', :as => 'subject_show'
  
  get 'uk-treaties/parties' => 'party#index', :as => 'party_list'
  get 'uk-treaties/parties/:party' => 'party#show', :as => 'party_show'
  get 'uk-treaties/parties/:party/actions' => 'party#action_list', :as => 'party_action_list'
  get 'uk-treaties/parties/:party/treaties' => 'party#treaty_list', :as => 'party_treaty_list'
  
  get 'uk-treaties/action-types' => 'action_type#index', :as => 'action_type_list'
  get 'uk-treaties/action-types/:action_type' => 'action_type#show', :as => 'action_type_show'
  
  get 'uk-treaties/locations' => 'location#index', :as => 'location_list'
  get 'uk-treaties/locations/:location' => 'location#show', :as => 'location_show'
  
  get 'uk-treaties/colophon' => 'colophon#index', :as => 'colophon_list'
  get 'uk-treaties/privacy-policy' => 'privacy#index', :as => 'privacy_list'
  
  get 'uk-treaties/meta' => 'meta#index', :as => 'meta_list'
  get 'uk-treaties/meta/cookies' => 'meta#cookies', :as => 'meta_cookies'
end

app/controllers/treaty_type_controller.rb
class TreatyTypeController < ApplicationController
  
  def index
    @treaty_types = TreatyType.all
    @page_title = 'Treaty types'
  end
  
  def show
    treaty_type = params[:treaty_type]
    @treaty_type = TreatyType.find( treaty_type )
    @page_title = "#{@treaty_type.label} treaties"
  end
end

app/views/treaty_type/_treaty_type.html.erb
<%= content_tag( 'li', link_to( treaty_type.label, treaty_type_show_url( :treaty_type => treaty_type ) ) ) %>

app/views/treaty_type/index.html.erb
<%= content_tag( 'h1', 'Treaty types' ) %>
<ol>
	<%= render :partial => 'treaty_type', :collection => @treaty_types %>
</ol>

app/views/treaty_type/show.html.erb
<%= content_tag( 'h1', @treaty_type.label ) %>

<%= content_tag( 'h2', 'Treaties' ) %>
<table>
	<%= render :partial => 'treaty/table_header' %>
	<tbody>
		<%= render :partial => 'treaty/treaty', :collection => @treaty_type.treaties %>
	</tbody>
</table>