config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'home#index'

  get 'uk-treaties/' => 'home#index', :as => 'home'
  
  get 'uk-treaties/treaties' => 'treaty#index', :as => 'treaty_list'
  get 'uk-treaties/treaties/:treaty' => 'treaty#show', :as => 'treaty_show'
  
  get 'uk-treaties/treaty-types' => 'treaty_type#index', :as => 'treaty_type_list'
  get 'uk-treaties/treaty-types/:treaty_type' => 'treaty_type#show', :as => 'treaty_type_show'
  
  get 'uk-treaties/subjects' => 'subject#index', :as => 'subject_list'
  get 'uk-treaties/subjects/:subject' => 'subject#show', :as => 'subject_show'
  
  get 'uk-treaties/parties' => 'party#index', :as => 'party_list'
  get 'uk-treaties/parties/:party' => 'party#show', :as => 'party_show'
  get 'uk-treaties/parties/:party/actions' => 'party#action_list', :as => 'party_action_list'
  get 'uk-treaties/parties/:party/treaties' => 'party#treaty_list', :as => 'party_treaty_list'
  
  get 'uk-treaties/action-types' => 'action_type#index', :as => 'action_type_list'
  get 'uk-treaties/action-types/:action_type' => 'action_type#show', :as => 'action_type_show'
  
  get 'uk-treaties/locations' => 'location#index', :as => 'location_list'
  get 'uk-treaties/locations/:location' => 'location#show', :as => 'location_show'
  
  get 'uk-treaties/colophon' => 'colophon#index', :as => 'colophon_list'
  get 'uk-treaties/privacy-policy' => 'privacy#index', :as => 'privacy_list'
  
  get 'uk-treaties/meta' => 'meta#index', :as => 'meta_list'
  get 'uk-treaties/meta/cookies' => 'meta#cookies', :as => 'meta_cookies'
end

app/controllers/meta_controller.rb
class MetaController < ApplicationController
  
  def index
    @page_title = 'About this website'
  end
  
  def cookies
    @page_title = 'Cookies'
  end
end

app/views/meta/cookies.html.erb
<%= content_tag( 'h1', 'Cookies' ) %>

<%= content_tag( 'p', "Cookies are small text files which are placed on your device when you visit our website. Some cookies are essential for the site to work properly, whilst others can provide useful feedback by letting us see how our services are being used." ) %>

<%= content_tag( 'h2', 'Essential cookies' ) %>

<%= content_tag( 'p', "Essential (or 'strictly necessary’) cookies allow you to move around our website and use its features and/or services. These cookies always need to be on as they help to make our website work. Essential cookies are a site's basic form of memory, so they do things like remember if you are logged in to a part of the website." ) %>

<%= content_tag( 'p', "You may be able to block these cookies by changing the preferences on your browser, but this may limit you from accessing our online services." ) %>

<%= content_tag( 'h2', 'Cloudflare' ) %>
 
<%= content_tag( 'p', "In addition, we use cookies to support our Content Delivery Network, Cloudflare. These cookies are used to identify individual clients behind a shared IP address and apply security settings on a per-client basis." ) %>

<div class="table-wrapper">
	<table class="multibody">
		<tbody>
			<tr>
				<%= content_tag( 'th', 'Name:' ) %>
				<%= content_tag( 'td', '_cf_bm' ) %>
			</tr>
			<tr>
				<%= content_tag( 'th', 'Purpose:' ) %>
				<%= content_tag( 'td', 'Bot management.' ) %>
			</tr>
			<tr>
				<%= content_tag( 'th', 'Expires:' ) %>
				<%= content_tag( 'td', 'After 30 minutes of continuous inactivity.' ) %>
			</tr>
		</tbody>
		<tbody>
			<tr>
				<%= content_tag( 'th', 'Name:' ) %>
				<%= content_tag( 'td', '_cfuvid' ) %>
			</tr>
			<tr>
				<%= content_tag( 'th', 'Purpose:' ) %>
				<%= content_tag( 'td', 'Rate limiting.' ) %>
			</tr>
			<tr>
				<%= content_tag( 'th', 'Expires:' ) %>
				<%= content_tag( 'td', 'When user exits browser.' ) %>
			</tr>
		</tbody>
		<tbody>
			<tr>
				<%= content_tag( 'th', 'Name:' ) %>
				<%= content_tag( 'td', 'cf_clearance' ) %>
			</tr>
			<tr>
				<%= content_tag( 'th', 'Purpose:' ) %>
				<%= content_tag( 'td', 'Clearance Cookie stores the proof of challenge passed. It is used to no longer issue a challenge if present. It is required to reach an origin server.' ) %>
			</tr>
			<tr>
				<%= content_tag( 'th', 'Expires:' ) %>
				<%= content_tag( 'td', 'After 30 minutes of continuous inactivity.' ) %>
			</tr>
		</tbody>
	</table>
</div>

<%= content_tag( 'p', "For more details on cookies in use across the Parliament website, please visit the #{link_to( 'UK Parliament Cookie Policy page', 'https://www.parliament.uk/site-information/privacy/' )}.".html_safe ) %>

app/views/meta/index.html.erb
<%= content_tag( 'h1', 'About this website' ) %>

<ul>
	<%= content_tag( 'li', link_to( 'Cookies', meta_cookies_url ) ) %>
</ul>