config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'home#index'

  get 'uk-treaties/' => 'home#index', :as => 'home'
  
  get 'uk-treaties/treaties' => 'treaty#index', :as => 'treaty_list'
  get 'uk-treaties/treaties/:treaty' => 'treaty#show', :as => 'treaty_show'
  
  get 'uk-treaties/treaty-types' => 'treaty_type#index', :as => 'treaty_type_list'
  get 'uk-treaties/treaty-types/:treaty_type' => 'treaty_type#show', :as => 'treaty_type_show'
  
  get 'uk-treaties/subjects' => 'subject#index', :as => 'subject_list'
  get 'uk-treaties/subjects/:subject' => 'subject#show', :as => 'subject_show'
  
  get 'uk-treaties/parties' => 'party#index', :as => 'party_list'
  get 'uk-treaties/parties/:party' => 'party#show', :as => 'party_show'
  get 'uk-treaties/parties/:party/actions' => 'party#action_list', :as => 'party_action_list'
  get 'uk-treaties/parties/:party/treaties' => 'party#treaty_list', :as => 'party_treaty_list'
  
  get 'uk-treaties/action-types' => 'action_type#index', :as => 'action_type_list'
  get 'uk-treaties/action-types/:action_type' => 'action_type#show', :as => 'action_type_show'
  
  get 'uk-treaties/locations' => 'location#index', :as => 'location_list'
  get 'uk-treaties/locations/:location' => 'location#show', :as => 'location_show'
  
  get 'uk-treaties/colophon' => 'colophon#index', :as => 'colophon_list'
  get 'uk-treaties/privacy-policy' => 'privacy#index', :as => 'privacy_list'
  
  get 'uk-treaties/meta' => 'meta#index', :as => 'meta_list'
  get 'uk-treaties/meta/cookies' => 'meta#cookies', :as => 'meta_cookies'
end

app/models/action_type.rb
# == Schema Information
#
# Table name: action_types
#
#  id    :integer          not null, primary key
#  label :string(255)      not null
#
class ActionType < ApplicationRecord
  
  has_many :actions,
    -> { order( 'action_on, effective_on' ) }
end

app/views/action/_action_from_action_type.html.erb
<tr>
	<%= content_tag( 'td', link_to( action_from_action_type.treaty.title, treaty_show_url( :treaty => action_from_action_type.treaty ) ) ) %>
	<%= content_tag( 'td', link_to( action_from_action_type.party.name, party_show_url( :party => action_from_action_type.party ) ) ) %>
	<%= content_tag( 'td', action_from_action_type.action_on_display ) %>
	<%= content_tag( 'td', action_from_action_type.effective_on_display ) %>
</tr>

app/views/action/_action_from_party.html.erb
<tr>
	<%= content_tag( 'td', link_to( action_from_party.treaty.title, treaty_show_url( :treaty => action_from_party.treaty ) ) ) %>
	<td>
		<% if action_from_party.action_type -%>
			<%= link_to( action_from_party.action_type.label, action_type_show_url( :action_type => action_from_party.action_type ) ) %>
		<% end -%>
	</td>
	<%= content_tag( 'td', action_from_party.action_on_display ) %>
	<%= content_tag( 'td', action_from_party.effective_on_display ) %>
</tr>

app/views/action/_action_from_treaty.html.erb
<tr>
	<%= content_tag( 'td', link_to( action_from_treaty.party.name, party_show_url( :party => action_from_treaty.party ) ) ) %>
	<td>
		<% if action_from_treaty.action_type -%>
			<%= link_to( action_from_treaty.action_type.label, action_type_show_url( :action_type => action_from_treaty.action_type ) ) %>
		<% end -%>
	</td>
	<%= content_tag( 'td', action_from_treaty.action_on_display ) %>
	<%= content_tag( 'td', action_from_treaty.effective_on_display ) %>
</tr>