config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'home#index'

  get 'uk-treaties/' => 'home#index', :as => 'home'
  
  get 'uk-treaties/treaties' => 'treaty#index', :as => 'treaty_list'
  get 'uk-treaties/treaties/:treaty' => 'treaty#show', :as => 'treaty_show'
  
  get 'uk-treaties/treaty-types' => 'treaty_type#index', :as => 'treaty_type_list'
  get 'uk-treaties/treaty-types/:treaty_type' => 'treaty_type#show', :as => 'treaty_type_show'
  
  get 'uk-treaties/subjects' => 'subject#index', :as => 'subject_list'
  get 'uk-treaties/subjects/:subject' => 'subject#show', :as => 'subject_show'
  
  get 'uk-treaties/parties' => 'party#index', :as => 'party_list'
  get 'uk-treaties/parties/:party' => 'party#show', :as => 'party_show'
  get 'uk-treaties/parties/:party/actions' => 'party#action_list', :as => 'party_action_list'
  get 'uk-treaties/parties/:party/treaties' => 'party#treaty_list', :as => 'party_treaty_list'
  
  get 'uk-treaties/action-types' => 'action_type#index', :as => 'action_type_list'
  get 'uk-treaties/action-types/:action_type' => 'action_type#show', :as => 'action_type_show'
  
  get 'uk-treaties/locations' => 'location#index', :as => 'location_list'
  get 'uk-treaties/locations/:location' => 'location#show', :as => 'location_show'
  
  get 'uk-treaties/colophon' => 'colophon#index', :as => 'colophon_list'
  get 'uk-treaties/privacy-policy' => 'privacy#index', :as => 'privacy_list'
  
  get 'uk-treaties/meta' => 'meta#index', :as => 'meta_list'
  get 'uk-treaties/meta/cookies' => 'meta#cookies', :as => 'meta_cookies'
end

app/models/party.rb
# == Schema Information
#
# Table name: parties
#
#  id             :integer          not null, primary key
#  downcased_name :string(255)      not null
#  name           :string(255)      not null
#
class Party < ApplicationRecord

  has_many :actions,
    -> { order( 'action_on, effective_on' ) }
  has_many :treaty_parties
  has_many :treaties,
    -> { order( 'signed_on, in_force_on' ) },
  :through => :treaty_parties
end

app/controllers/party_controller.rb
class PartyController < ApplicationController
  
  def index
    @parties = Party.all.order( 'name' )
    @page_title = 'Parties'
  end
  
  def show
    party = params[:party]
    @party = Party.find( party )
    @page_title = "Parties - #{@party.name}"
  end
  
  def action_list
    party = params[:party]
    @party = Party.find( party )
    @page_title = "Actions by #{@party.name}"
  end
  
  def treaty_list
    party = params[:party]
    @party = Party.find( party )
    @page_title = "Treaties with #{@party.name}"
  end
end

app/views/party/_party.html.erb
<%= content_tag( 'li', link_to( party.name, party_show_url( :party => party ) ) ) %>

app/views/party/action_list.html.erb
<%= content_tag( 'h1', "#{@party.name} - Actions" ) %>
<table>
	<thead>
		<tr>
			<%= content_tag( 'th', 'Agreement' ) %>
			<%= content_tag( 'th', 'Action type' ) %>
			<%= content_tag( 'th', 'Action on' ) %>
			<%= content_tag( 'th', 'Effective on' ) %>
		</tr>
	</thead>
	<tbody>
		<%= render :partial => 'action/action_from_party', :collection => @party.actions %>
	</tbody>
</table>
		

app/views/party/index.html.erb
<%= content_tag( 'h1', 'Parties' ) %>
<ol>
	<%= render :partial => 'party', :collection => @parties %>
</ol>

app/views/party/show.html.erb
<%= content_tag( 'h1', @party.name ) %>

<ul>
	<%= content_tag( 'li', link_to( "Treaties (#{@party.treaties.count})", party_treaty_list_url ) ) %>
	<%= content_tag( 'li', link_to( "Actions (#{@party.actions.count})", party_action_list_url ) ) %>
</ul>
		

app/views/party/treaty_list.html.erb
<%= content_tag( 'h1', "#{@party.name} - Treaties" ) %>

<table>
	<%= render :partial => 'treaty/table_header' %>
	<tbody>
		<%= render :partial => 'treaty/treaty', :collection => @party.treaties %>
	</tbody>
</table>